oidc:
  issuer-uri: https://dev-388275.oktapreview.com/oauth2/auskpi1fnzgPD6i6N0h7
  jwk-set-uri: https://dev-388275.oktapreview.com/oauth2/auskpi1fnzgPD6i6N0h7/v1/keys
  client-id: 0oajfcjaxs1OKu2kC0h7
  client-secret: bd5iKqHzaRc9Fv6lY_XyzEenpD4v9WT2k9XYdtF1

spring:
  application:
    name: payments
  profiles:
    active: native
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer-uri}
          jwk-set-uri: ${oidc.jwk-set-uri}

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    ROOT: debug
    org.springframework.web: trace
    reactor.core.publisher: trace