spring:
  application:
    name: frontend-microservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true