spring:
  application:
    name: frontend
  profiles:
    active: native

server:
  port: 0
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}