oidc:
  issuer-uri: https://dev-388275.oktapreview.com/oauth2/default
  client-id: 0oajfcjaxs1OKu2kC0h7
  client-secret: bd5iKqHzaRc9Fv6lY_XyzEenpD4v9WT2k9XYdtF1

spring:
  application:
    name: frontend
  profiles:
    active: native
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${oidc.issuer-uri}
#            authorization-uri: https://dev-388275.oktapreview.com/oauth2/default/v1/authorize
#            token-uri: https://dev-388275.oktapreview.com/oauth2/default/v1/token
#            user-info-uri: https://dev-388275.oktapreview.com/oauth2/default/v1/userinfo
#            jwk-set-uri: https://dev-388275.oktapreview.com/oauth2/default/v1/keys
        registration:
          okta:
            client-id: ${oidc.client-id}
            client-secret: ${oidc.client-secret}
            scope: openid, email, profile
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer-uri}
          jwk-set-uri: https://dev-388275.oktapreview.com/oauth2/default/v1/keys


server:
  port: 0
  servlet:
    contextPath: /frontend

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}