# okta properties
#oidc:
#  issuer-uri: https://dev-388275.oktapreview.com/oauth2/default
#  client-id: 0oajfcjaxs1OKu2kC0h7
#  client-secret: bd5iKqHzaRc9Fv6lY_XyzEenpD4v9WT2k9XYdtF1
#
#okta:
#  oauth2:
#    audience: frontend
#    issuer: https://dev-388275.oktapreview.com/oauth2/default
#    client-id: ${oidc.client-id}
#    client-secret: ${oidc.client-secret}
#    scope: openid, email, profile

spring:
  application:
    name: frontend-microservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    ROOT: info
    org.springframework.web: info