version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.dropwizard.metrics:metrics-core
    versions:
    - 4.1.17
    - 4.1.18
    - 4.1.19
  - dependency-name: org.springframework.data:spring-data-r2dbc
    versions:
    - 1.3.0-M2
    - 1.3.0-M4
    - 1.3.0-M5
    - 1.3.0-RC1
  - dependency-name: io.micrometer:micrometer-core
    versions:
    - 1.6.3
    - 1.6.4
    - 1.6.5
  - dependency-name: org.springframework.boot:spring-boot-starter-data-cassandra-reactive
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-common
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
