steps:
  # This step builds the container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '--file=frontend/Dockerfile'
      - '--cache-from'
      - 'eu.gcr.io/vote-of-confidence-233210/voc-frontend:latest'
      - '-t'
      - 'eu.gcr.io/vote-of-confidence-233210/voc-frontend:$SHORT_SHA'
      - '-t'
      - 'eu.gcr.io/vote-of-confidence-233210/voc-frontend:latest'
      - '.'
    waitFor: ['-']
  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'eu.gcr.io/vote-of-confidence-233210/voc-frontend:$SHORT_SHA'
    wait_for: ['Build']
  - name: 'gcr.io/cloud-builders/docker'
    id: PushLatest
    args:
      - 'push'
      - 'eu.gcr.io/vote-of-confidence-233210/voc-frontend:latest'
    wait_for: ['Build']
  # Jib mvn
  - name: 'gcr.io/cloud-builders/git'
    id: CloneSRC
    args: ['clone', 'https://github.com/mrzo0m/vote_of_confidence']
    env: ['PROJECT_ROOT=voc']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/mvn'
    id: MvnJib
    args: ['package','-P', 'containerizing-gcr']
    waitFor: ['CloneSRC']
images:
  - 'eu.gcr.io/vote-of-confidence-233210/voc-frontend:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-communications:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-gateway:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-history:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-notifications:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-payments:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-reporting:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-scheduling:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-trace:latest'
  - 'eu.gcr.io/vote-of-confidence-233210/voc-tracker:latest'
timeout: '1800s'