steps:

  #############################################

  - name: 'gcr.io/cloud-builders/docker'
    id: build-frontend
    args:
      - 'build'
      - '--no-cache'
      - '--file=frontend/Dockerfile'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/voc-frontend:$SHORT_SHA'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/voc-frontend:latest'
      - '.'
    waitFor: ['-']
  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: push-frontend
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/voc-frontend:$SHORT_SHA'
    wait_for: ['build-frontend']
  - name: 'gcr.io/cloud-builders/docker'
    id: push-frontend-latest
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/voc-frontend:latest'
    wait_for: ['build-frontend']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: deploy-frontend-latest
    args:
      - 'set'
      - 'image'
      - 'deployment/frontend-deployment'
      - 'frontend-microservice=eu.gcr.io/$PROJECT_ID/voc-frontend:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=voc-cluster-1'
    wait_for: ['push-frontend']

  #############################################
#
#
#  #############################################
#
  - name: 'gcr.io/cloud-builders/docker'
    id: build-gateway
    args:
      - 'build'
      - '--no-cache'
      - '--file=gateway/Dockerfile'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/voc-gateway:$SHORT_SHA'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/voc-gateway:latest'
      - '.'
    waitFor: ['-']
  # This step pushes the image to Container Registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: push-gateway
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/voc-gateway:$SHORT_SHA'
    wait_for: ['build-gateway']
  - name: 'gcr.io/cloud-builders/docker'
    id: push-gateway-latest
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/voc-gateway:latest'
    wait_for: ['build-gateway']
  - name: 'gcr.io/cloud-builders/kubectl'
    id: deploy-gateway-latest
    args:
      - 'set'
      - 'image'
      - 'deployment/gateway-deployment'
      - 'gateway-microservice=eu.gcr.io/$PROJECT_ID/voc-gateway:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=voc-cluster-1'
    wait_for: ['push-gateway']
#
#  #############################################

#  - name: 'gcr.io/cloud-builders/docker'
#    id: build-history
#    args:
#      - 'build'
#      - '--no-cache'
#      - '--file=history/Dockerfile'
#      - '-t'
#      - 'eu.gcr.io/$PROJECT_ID/voc-history:$SHORT_SHA'
#      - '-t'
#      - 'eu.gcr.io/$PROJECT_ID/voc-history:latest'
#      - '.'
#    waitFor: ['-']
#  # This step pushes the image to Container Registry
#  # The PROJECT_ID and SHORT_SHA variables are automatically
#  # replaced by Cloud Build.
#  - name: 'gcr.io/cloud-builders/docker'
#    id: push-history
#    args:
#      - 'push'
#      - 'eu.gcr.io/$PROJECT_ID/voc-history:$SHORT_SHA'
#    wait_for: ['build-history']
#  - name: 'gcr.io/cloud-builders/docker'
#    id: push-history-latest
#    args:
#      - 'push'
#      - 'eu.gcr.io/$PROJECT_ID/voc-history:latest'
#    wait_for: ['build-history']
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: deploy-history-latest
#    args:
#      - 'set'
#      - 'image'
#      - 'deployment/history-deployment'
#      - 'history-microservice=eu.gcr.io/$PROJECT_ID/voc-history:$SHORT_SHA'
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=voc-cluster-1'
#    wait_for: ['push-history']

  #  #############################################

#  - name: 'gcr.io/cloud-builders/docker'
#    id: build-tracker
#    args:
#      - 'build'
#      - '--no-cache'
#      - '--file=tracker/Dockerfile'
#      - '-t'
#      - 'eu.gcr.io/$PROJECT_ID/voc-tracker:$SHORT_SHA'
#      - '-t'
#      - 'eu.gcr.io/$PROJECT_ID/voc-tracker:latest'
#      - '.'
#    waitFor: ['-']
#  # This step pushes the image to Container Registry
#  # The PROJECT_ID and SHORT_SHA variables are automatically
#  # replaced by Cloud Build.
#  - name: 'gcr.io/cloud-builders/docker'
#    id: push-tracker
#    args:
#      - 'push'
#      - 'eu.gcr.io/$PROJECT_ID/voc-tracker:$SHORT_SHA'
#    wait_for: ['build-tracker']
#  - name: 'gcr.io/cloud-builders/docker'
#    id: push-tracker-latest
#    args:
#      - 'push'
#      - 'eu.gcr.io/$PROJECT_ID/voc-tracker:latest'
#    wait_for: ['build-tracker']
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: deploy-tracker-latest
#    args:
#      - 'set'
#      - 'image'
#      - 'deployment/tracker-deployment'
#      - 'tracker-microservice=eu.gcr.io/$PROJECT_ID/voc-tracker:$SHORT_SHA'
#    env:
#      - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-c'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=voc-cluster-1'
#    wait_for: ['push-tracker']


  ##########################################

#
#  - name: 'gcr.io/$PROJECT_ID/slackbot'
#    id: chatops
#    args: [ '--build', '$BUILD_ID',
#            '--webhook', 'https://hooks.slack.com/services/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' ]
#    wait_for: ['deploy-gateway-latest', 'deploy-history-latest', 'deploy-frontend-latest']


images:
  - 'eu.gcr.io/$PROJECT_ID/voc-frontend:latest'
  - 'eu.gcr.io/$PROJECT_ID/voc-gateway:latest'
#  - 'eu.gcr.io/$PROJECT_ID/voc-history:latest'
#  - 'eu.gcr.io/$PROJECT_ID/voc-tracker:latest'
timeout: '1800s'
