apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice
          image: eu.gcr.io/vote-of-confidence-233210/voc-gateway:latest
          ports:
            - containerPort: 8080