apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice
          image: eu.gcr.io/vote-of-confidence-233210/voc-gateway:latest
          volumeMounts:
            # name must match the volume name below
            - name: secret-volume
              mountPath: /etc/secret-volume
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
      volumes:
        - name: secret-volume
          secret:
            secretName: votumdoveriya-rf-tls