apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-microservice
  template:
    metadata:
      labels:
        app: frontend-microservice
    spec:
      containers:
        - name: frontend-microservice
          image: eu.gcr.io/vote-of-confidence-233210/voc-frontend:latest
          volumeMounts:
            # name must match the volume name below
            - name: secret-volume
              mountPath: /etc/secret-volume
          ports:
            - containerPort: 8080
            - containerPort: 443
          resources:
            requests:
              cpu: 100m
        # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: secret-volume
          secret:
            secretName: votumdoveriya-rf-tls