apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-microservice
  template:
    metadata:
      labels:
        app: frontend-microservice
    spec:
      containers:
        - name: frontend-microservice
          image: eu.gcr.io/vote-of-confidence-233210/voc-frontend:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/etc/nginx/ssl"
              name: nginx-ssl
              readOnly: true
          resources:
            requests:
              cpu: 100m
          volumes:
            - name: nginx-ssl
              secret:
                secretName: votumdoveriya-rf-tls