apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-microservice
  template:
    metadata:
      labels:
        app: gateway-microservice
    spec:
      containers:
        - name: gateway-microservice
          image: eu.gcr.io/vote-of-confidence-233210/voc-gateway:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SSL_KEY_PASS
              valueFrom:
                secretKeyRef:
                  name: domaincert
                  key: SSL_KEY_PASS
            - name: SSL_STORE_PASS
              valueFrom:
                secretKeyRef:
                  name: domaincert
                  key: SSL_STORE_PASS
          ports:
            - name: spring-boot
              containerPort: 8443
          resources:
            requests:
              cpu: 50m
