apiVersion: v1
kind: Service
metadata:
  name: gateway-lb-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080