apiVersion: v1
kind: Service
metadata:
  name: gateway-lb-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-microservice
  ports:
    - name: https
      nodePort: 30476
      port: 443
      protocol: TCP
      targetPort: nginx-https
    - name: http
      nodePort: 32761
      port: 80
      protocol: TCP
      targetPort: nginx-http