apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
        - name: mysql
          image: eu.gcr.io/vote-of-confidence-233210/mysql
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
              name: server
            - containerPort: 33060
              name: x-server
            - containerPort: 33061
              name: replica-group-check
            - containerPort: 22
              name: ssh
            - containerPort: 443
              name: key-service
            - containerPort: 11211
              name: memcached
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - if [[ -f /usr/src/pre-stop.sh ]]; then /bin/sh -c /usr/src/pre-stop.sh; fi
          env:
            - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-pass
                    key: password
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: voc-storageclass-mysql
        resources:
          requests:
            storage: 1Gi