apiVersion: v1
kind: Service
metadata:
  name: frontend-microservice
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30101
  selector:
    app: frontend-microservice
  type: NodePort
