apiVersion: v1
kind: Service
metadata:
  name: history-microservice
spec:
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30102
  selector:
    app: history-microservice
  type: NodePort