apiVersion: v1
          kind: Service
          metadata:
            name: tracker-microservice
          spec:
            ports:
              - port: 80
                targetPort: 8000
                nodePort: 30103
            selector:
              app: tracker-microservice
            type: NodePort