apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice
spec:
  type: NodePort
  ports:
    - nodePort: 30100
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: gateway-microservice
