apiVersion: v1
kind: Service
metadata:
  name: frontend-microservice
spec:
  ports:
    - name: http
      port: 80
      targetPort: nginx-http
      protocol: TCP
  selector:
    app: frontend-microservice
  type: NodePort
