apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice
spec:
  type: NodePort
  ports:
    - nodePort: 30100
      port: 8080
      targetPort: 8080
  selector:
    app: gateway-microservice
