apiVersion: v1
kind: Service
metadata:
  name: frontend-microservice
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
      nodePort: 30101
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
      nodePort: 30104
  selector:
    app: frontend-microservice
  type: NodePort
