apiVersion: v1
kind: Service
metadata:
  name: frontend-microservice
spec:
  ports:
    - name: https
      port: 443
      targetPort: nginx-https
      protocol: TCP
    - name: http
      port: 80
      targetPort: nginx-http
      protocol: TCP
  selector:
    app: frontend-microservice
  type: NodePort
